### PR TITLE
commenting out the 'WO' registers

### PR DESCRIPTION
**Pull request by ruck314**
### Description
commenting out the 'WO' registers for the TPGMiniCore.py and TPGMiniCore.yaml

### CODE REVIEW

**Comment by till-s** [comment]
Not sure what the purpose of commenting the WO registers is. If it is a short-term work-around until these registers have been converted to RW-style then it's OK - but the real fix should IMO encompass:

- collapse pulseIdRd/pulseIdWr into a single (RW) register; alternatively the pulseIdRd register could reflect the 'running' pulseId and pulseIdWr should read back whatever was last written there. In that case pulseIdRd would be RO, pulseIdWR RW
- same for TStampRd/TStampWr -> TStamp
- convert  the single bits (RateReload, TxReset) into RW bits where 1 must be written to have an effect, readback value is 0.
- In case of BsaComplete I'm not sure what the readback bit actually reflects. But it could probably be left as-is and the BsaCompleteWr bit could be treated the same way as RateReload & friends.

NOTE: all of the above in some way writeable registers should be marked as not cacheable:
   cacheable: NOT_CACHEABLE
since e.g., multiple writes to TStampWr with the same (cached) value would have a side-effect.

**Comment by ruck314** [comment]
Alternatively, we could move these WO registers to a different offset to prevent RO and WO being mapped to the same memory address space

**Comment by thatweaver** [comment]
Having WO registers at a different offset is exactly the condition now that is causing a problem.  The software attempts to read them.  If the notion of WO is not respected by software, then we should just eliminate it like Till has outlined.  I think Till's suggestion will work fine.  The PulseIdRd and PulseIdWr distinction is already in the YAML, so software won't break if we split their offsets.

**Comment by till-s** [comment]
I would much prefer to avoid WO registers. They create several potential problems. E.g., in a GUI the user expects to 'see something' even for a WO register. How do you initialize that visual feedback if you can't read the register? The register implementor is in the best position to design the semantics of a readback operation and if we decide that we require a readback then the designer has to think about it early on. IMO that would be desirable.

**Comment by slacrherbst** [comment]
Ben and I have discussed the 8 bit resolution and think it would become problematic to try to support.

WO registers should be fine. We run into problems when two functions are mapped to the same bit. For example a counter which is cleared on write. We should avoid this in firmware.

**Comment by ruck314** [comment]
Reverted back the changes (282d62d) since it sounds like we want to take a different CPSW strategy than just commenting out the WO registers. 
@till-s Can you create a pull request that has the CPSW updates needed to fix this issue?  Thanks.

**Pull request closed without merging**
